[versions]
kotlin = "2.4.20"
json = "1.0.9"

[libraries]
json = { module = "io.github.alexeykozyakov.json:json", version.ref = "json"}
json-reflect = { module = "io.github.alexeykozyakov.json:json-reflect", version.ref = "json"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
